// Semilla inicial de Brújula — las 43 tareas y la configuración real que ya
// existían en el Artifact de claude.ai antes de migrar a este backend
// propio. Se usa UNA sola vez (ver sembrarBrujulaInicial en db/crm.js): si
// ya hay datos guardados, esto nunca los pisa.
export const brujulaSemilla = {
  "areas": [
    "Técnico",
    "Obra",
    "Cotizaciones & Compras",
    "Comercial",
    "Mercadeo",
    "Administrativo",
    "Jurídico",
    "Contable"
  ],
  "people": [
    "Ana",
    "Diana",
    "Santiago"
  ],
  "tasks": [
    {
      "id": "t1",
      "no": 1,
      "area": "Técnico",
      "actividad": "Loteo zona A",
      "detalle": "Definir cuáles son los lotes correspondientes a la zona A.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": "2026-08-13",
      "observacion": "se esta a la espera del plano de alexander vega, tiene 24 lotes vendidos y 4 lotes para SDL",
      "dueno": "Ana",
      "colaboradores": [
        "Diana",
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": true,
      "valorEjecutado": null
    },
    {
      "id": "t2",
      "no": 2,
      "area": "Técnico",
      "actividad": "Movimiento de tierras",
      "detalle": "Consolidar cantidades y cotización total del movimiento de tierras; incluir zonas R y N.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t3",
      "no": 3,
      "area": "Técnico",
      "actividad": "Diseño hidráulico e hidrosanitario",
      "detalle": "Continuar diseño de red hidráulica para 230 lotes y entregar cantidades/presupuesto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-13",
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Diana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t4",
      "no": 4,
      "area": "Técnico",
      "actividad": "Presupuesto general de obra",
      "detalle": "Actualizar costos directos e indirectos con cantidades hidrosanitarias y movimiento de tierras.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t5",
      "no": 5,
      "area": "Técnico",
      "actividad": "Red eléctrica",
      "detalle": "Definir/iniciar diseño de red eléctrica y validar factibilidad/costos.",
      "cantidad": 1,
      "valorUnitario": 6000000,
      "fechaInicio": "2026-09-10",
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana",
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t6",
      "no": 6,
      "area": "Técnico",
      "actividad": "Lindero cascada La Laja",
      "detalle": "Definir técnicamente el lindero en la cascada La Laja.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Diana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t7",
      "no": 7,
      "area": "Técnico",
      "actividad": "Gestión de agua",
      "detalle": "Reunion Gestion Acueducto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-18",
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana",
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t8",
      "no": 8,
      "area": "Obra",
      "actividad": "Adecuación sala de ventas",
      "detalle": "Completar aseo, puerta, plantas, planos, tubo y compras pendientes.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": "2026-08-19",
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana",
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t9",
      "no": 9,
      "area": "Obra",
      "actividad": "Sala de ventas – desagüe",
      "detalle": "Instalar desagüe definitivo para controlar humedad.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t10",
      "no": 10,
      "area": "Obra",
      "actividad": "Baranda plataforma",
      "detalle": "Cotizar material y ejecutar baranda. Mano de obra estimada $300.000.",
      "cantidad": 1,
      "valorUnitario": 300000,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": "2026-08-13",
      "observacion": "se va a ubicar arbol posiblemente pino o eucalipto zona ",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t11",
      "no": 11,
      "area": "Obra",
      "actividad": "Vías zonas R y N",
      "detalle": "Completar apertura/terminación de vías; definir maquinaria y programación.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t12",
      "no": 12,
      "area": "Obra",
      "actividad": "Relleno de piscina",
      "detalle": "Definir cantidad de viajes/material y ejecutar relleno.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t13",
      "no": 13,
      "area": "Obra",
      "actividad": "Senderos – guadua",
      "detalle": "Realizar corte y tapón de guaduas en senderos.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t14",
      "no": 14,
      "area": "Obra",
      "actividad": "Zona de cascadas",
      "detalle": "Adecuar y limpiar zona de cascadas.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t15",
      "no": 15,
      "area": "Obra",
      "actividad": "Fumigación general",
      "detalle": "Continuar fumigación del terreno y vías.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t16",
      "no": 16,
      "area": "Obra",
      "actividad": "Muelle – talud",
      "detalle": "Empradizar el talud del muelle.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t17",
      "no": 17,
      "area": "Obra",
      "actividad": "Sala de ventas – árbol",
      "detalle": "Cortar árbol cercano a la sala de ventas, previa verificación de seguridad.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t18",
      "no": 18,
      "area": "Obra",
      "actividad": "Jardinería sendero/lago",
      "detalle": "Ejecutar siembra definida: salvia morada, lantanas y material vegetal; coordinar jornal.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-08",
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t19",
      "no": 19,
      "area": "Obra",
      "actividad": "Vivero",
      "detalle": "Definir y adecuar vivero para material vegetal del proyecto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t20",
      "no": 20,
      "area": "Cotizaciones & Compras",
      "actividad": "Maquinaria movimiento de tierras",
      "detalle": "Cerrar cotización por horas de bulldozer D6 y equipos requeridos.",
      "cantidad": 24,
      "valorUnitario": 180000,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t21",
      "no": 21,
      "area": "Cotizaciones & Compras",
      "actividad": "Portería y portón de acceso",
      "detalle": "Entregar diseños a Don Fabián, reunirse y cerrar cotización/alcance de ejecución.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Diana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t22",
      "no": 22,
      "area": "Cotizaciones & Compras",
      "actividad": "Arreglos vehículo",
      "detalle": "Cotizar arreglos requeridos para el Daihatsu/vehículo del proyecto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t23",
      "no": 23,
      "area": "Comercial",
      "actividad": "Meta de visitas",
      "detalle": "Estructurar plan para alcanzar 70 visitas/mes y mejorar cierre desde el primer contacto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Equipo Comercial",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t24",
      "no": 24,
      "area": "Comercial",
      "actividad": "CRM y base de leads",
      "detalle": "Depurar base de datos, revisar seguimiento de Paola y asegurar trazabilidad de cada lead.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Santiago",
      "colaboradores": [
        "Paola"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t25",
      "no": 25,
      "area": "Comercial",
      "actividad": "Manual de ventas",
      "detalle": "Unificar pitch, precios, financiación y manejo de objeciones para todo el equipo.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Santiago",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t26",
      "no": 26,
      "area": "Comercial",
      "actividad": "Convenios empresariales",
      "detalle": "Reprogramar/realizar reunión con Harold y avanzar convenios (Comprocemva, Juriscop, Coasmedas u otros).",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Santiago",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t27",
      "no": 27,
      "area": "Comercial",
      "actividad": "Material para ferias",
      "detalle": "Definir e imprimir folletos y mapas; completar kit para ferias empresariales.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": "2026-08-19",
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Comercial"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t28",
      "no": 28,
      "area": "Mercadeo",
      "actividad": "Contenido audiovisual",
      "detalle": "Grabar piezas: financiación, pareja/siembra, distribución del lote y experiencia en proyecto.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-08",
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": "2026-08-12",
      "observacion": "se realizaron grabaciones a la espera de material",
      "dueno": "Ana",
      "colaboradores": [
        "Sebastián"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t29",
      "no": 29,
      "area": "Mercadeo",
      "actividad": "Campañas WhatsApp",
      "detalle": "Optimizar campañas según resultados: descanso/retiro, público 35+ y creativos de mejor desempeño.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Sebastián",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t30",
      "no": 30,
      "area": "Mercadeo",
      "actividad": "BOT y CRM",
      "detalle": "Revisar costo mensual aproximado de $350.000, desempeño y correcta derivación de pautas al bot.",
      "cantidad": 1,
      "valorUnitario": 350000,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Santiago",
      "colaboradores": [
        "Sebastián"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t31",
      "no": 31,
      "area": "Mercadeo",
      "actividad": "Adecuación vehículo",
      "detalle": "Completar branding/adecuación del vehículo del proyecto.",
      "cantidad": 1,
      "valorUnitario": 1500000,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t32",
      "no": 32,
      "area": "Administrativo",
      "actividad": "Plano final",
      "detalle": "Corregir plano final y dejar archivo listo para impresión/uso comercial.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t33",
      "no": 33,
      "area": "Administrativo",
      "actividad": "Programa contable y archivo",
      "detalle": "Completar digitalización de promesas de compraventa y actualización del programa contable.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-05",
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Paola",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t34",
      "no": 34,
      "area": "Administrativo",
      "actividad": "Pago aserrada de madera",
      "detalle": "Gestionar cuenta de cobro y pago pendiente de aserrada de madera.",
      "cantidad": 1,
      "valorUnitario": 700000,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "Se gestiona una vez se define el arbol de corte",
      "dueno": "Ana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t35",
      "no": 35,
      "area": "Administrativo",
      "actividad": "Pagos de jornales",
      "detalle": "Revisar y pagar jornales pendientes de Julián y otros trabajadores.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t36",
      "no": 36,
      "area": "Administrativo",
      "actividad": "Formato de seguimiento",
      "detalle": "Implementar este formato único y mantenerlo actualizado al 100% en cada reunión.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": "2026-08-12",
      "fechaEntrega": null,
      "estado": "EN PROCESO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Santiago"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t37",
      "no": 37,
      "area": "Jurídico",
      "actividad": "Reunión de seguimiento jurídico",
      "detalle": "Revisar subdivisión, avances, propietarios, consentimiento general, contrato de comunidad y términos/condiciones.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": "2026-08-14",
      "estado": "PROGRAMADO",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Santiago",
        "Leonardo"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t38",
      "no": 38,
      "area": "Jurídico",
      "actividad": "Radicación zonas R y K",
      "detalle": "Radicar documentación para iniciar subdivisión de las zonas R y K.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": "2026-08-15",
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Leonardo",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t39",
      "no": 39,
      "area": "Jurídico",
      "actividad": "Poderes",
      "detalle": "Completar firmas/poderes requeridos para los procesos de subdivisión.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "FINALIZADO",
      "ultimoSeguimiento": "2026-08-12",
      "observacion": "se iniciara con radicacion de derechos de cuota R,K",
      "dueno": "Diana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t40",
      "no": 40,
      "area": "Jurídico",
      "actividad": "Relación para escrituración",
      "detalle": "Actualizar y enviar relación/documentación para escrituración de zonas K y N.",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Diana",
      "colaboradores": [
        "Leonardo"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t41",
      "no": 41,
      "area": "Contable",
      "actividad": "Actualizacion Contabilidad",
      "detalle": "Entrega Informacion Contabilidad",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Diana",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t42",
      "no": 42,
      "area": "Contable",
      "actividad": "Actualizacion Contabilidad",
      "detalle": "subir informacion al programa contable",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Paola Mosquera",
      "colaboradores": [],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    },
    {
      "id": "t43",
      "no": 43,
      "area": "Contable",
      "actividad": "Actualizacion Contabilidad",
      "detalle": "Revision de recibos de egreso y soportes contables",
      "cantidad": null,
      "valorUnitario": null,
      "fechaInicio": null,
      "fechaEntrega": null,
      "estado": "PENDIENTE",
      "ultimoSeguimiento": null,
      "observacion": "",
      "dueno": "Ana",
      "colaboradores": [
        "Diana",
        "Paola"
      ],
      "prioridad": "Media",
      "dependeDeId": null,
      "hitoId": null,
      "esRiesgo": false,
      "valorEjecutado": null
    }
  ],
  "hitos": [],
  "presupuestos": {},
  "nextNo": 44,
  "nextHitoNo": 1,
  "updatedAt": null
};
